# Page settings

baseURL = "https://www.acatejr.com/"
languageCode = "en"
title = "acatejr.com"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-1064854-14"

[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Averill Cate, Jr"
        tagline = "Senior Software Engineer"        

    [params.contact]
        enable = true
        location = "Arizona"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "520-370-6997"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "acatejr@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.acatejr.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Data Science Certificate"
        university = "Indiana University"
        dates = "2017 - 2018"
        [[params.education.list]]
        degree = "PhD Natural Resources and Remote Sensing"
        university = "The University of Arizona"
        dates = "2004 - 2008"
        [[params.education.list]]
        degree = "MS Management Information Systems"
        university = "The Universtiy of Arizona"
        dates = "2002 - 2004"
        [[params.education.list]]
        degree = "MS Watershed Management and GIS"
        university = "The Universtiy of Arizona"
        dates = "1997 - 2000"
        [[params.education.list]]
        degree = "BS Surface Water Hydrology"
        university = "The Universtiy of New Hampshire"
        dates = "1983 - 1988"
    
    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Golf"
        [[params.interests.list]]
        name = "Bicycle Touring"
        [[params.interests.list]]
        name = "Travel"

    [params.summary]
        enable = true
        text = "Application Developer with more than 14 years of experience seeking a new opportunity. Educational background includes a Ph.D. in Geographic Information Science/Geoinformatics from the University of Arizona and two Master’s Degrees. Extensive experience applying new languages and/or technologies such as Drupal, Django, or CodeIgniter to environmental and/or natural-resource related projects. Well-developed skills with programming, GIS, and earth science, with a proven ability to use GIS programming tools to make earth-science data more accessible. Self-driven and motivated with a reputation for developing new ideas that benefit the organization. Driven to succeed with a track record of success delivering work that solves problem and/or saves money for the client."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Principal Applications Systems Analyst/Developer"
        dates = "1997 - Present"
        company = "The University of Arizona"
        details = "Developed programmed and maintained multiple intranet web-based applications used to support departmental business operations."
        [[params.experience.list.items]]
        details = "Developed Oracle, SQL Server and MySQL databases for desktop and web applications"
        [[params.experience.list.items]]
        details = "Developed and programmed a website called AZ REACH (www.reachmilitaryfamilies.org)."
        [[params.experience.list.items]]
        details = "Performed custom Drupal theming and custom module development; custom theming involves modifying CSS files and creating and editing images for the site using Photoshop."
        [[params.experience.list.items]]
        details = "Developed Drupal modules that required writing PHP code that integrates with the Drupal framework."
        [[params.experience.list.items]]
        details = "Developed and programmed custom Drupal modules that focus on building search tools for the website. Example: One module shows an image of the United States and users can pick a state, degree program, and major, and the search will find schools or training programs for the field the user is interested in for the selected state or states."
        [[params.experience.list.items]]
        details = "Created other research documents that are connected to the searchable metadata stored in the sites MySQL database."
        [[params.experience.list.items]]
        details = "Used HTML and CSS to implement new look and feel of website design."
        [[params.experience.list.items]]
        details = "Enabled website research document searching through metadata stored in the site's MySQL database."
        [[params.experience.list.items]]
        details = "Developed and program a custom research document module using Drupal’s PHP API so that site users could search documents based on different attributes associated with each document."
        [[params.experience.list.items]]
        details = "Programmed professional development learning modules that allowed site visitors to read online training materials and take online quizzes."
        [[params.experience.list.items]]
        details = "Created and presented research presentations for conferences in water resources, GIS, and natural resources."
        [[params.experience.list.items]]
        details = "Developed DotAGWA, a web application using C#.Net, Java/J2EE, ESRI’s ArcGIS Server, Oracle Database and the Oracle Database spatial components."
        [[params.experience.list.items]]
        details = "Wrote and published research papers published in the Natural Resources Conservation Service scientific publication database."
        [[params.experience.list.items]]
        details = "Designed and developed the Santa Rita Experimental Range study and document search interface."
        [[params.experience.list.items]]
        details = "Developed a desktop GIS application called GeoFac used to browse, search, and display via maps U.S. Census information."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2012 - 2015"
        company = "The City of Tucson, AZ"
        details = "Responsible for maintenance of existing software applications as well as the development of new applications"
        [[params.experience.list.items]]
        details = "Developed and programmed and maintained multiple intranet web-based applications used to support City of Tucson daily business operations."
        [[params.experience.list.items]]
        details = "Developed Oracle, SQL Server and MySQL databases for desktop and web applications"
        [[params.experience.list.items]]
        details = "Developed open-data REST based web-API feeds as part of City of Tucson's open data initiative."
        [[params.experience.list.items]]
        details = "Developed web application for tracking and monitoring of the City's residential and commercial permitting system"

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."


    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Golf, Bicycle Touring, Travel"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/acatejr"
        title = "acatejr"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/averill-cate-jr-4a5b113"
        title = "acatejr"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/acatejr"
        title = "@acatejr"

